/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ssp;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author ARYAN_PARTH
 */
public class frame4 extends javax.swing.JFrame {

int icode, p;
String bname, iname, t;
    private boolean ee;
    /**
     * Creates new form frame4
     */
    public frame4() {
        initComponents();
        try{Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/aryan","root","root");
            Statement stmt = con.createStatement();
        
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(null,e.getMessage());}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        If1 = new javax.swing.JInternalFrame();
        l3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        If2 = new javax.swing.JInternalFrame();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        If3 = new javax.swing.JInternalFrame();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(736, 459));
        setMinimumSize(new java.awt.Dimension(736, 459));
        setPreferredSize(new java.awt.Dimension(736, 459));
        getContentPane().setLayout(null);

        If1.setClosable(true);
        If1.setMaximumSize(new java.awt.Dimension(736, 459));
        If1.setMinimumSize(new java.awt.Dimension(736, 459));
        If1.setPreferredSize(new java.awt.Dimension(651, 450));
        If1.setVisible(false);
        If1.getContentPane().setLayout(null);

        l3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ssp/bb2128.jpg"))); // NOI18N
        l3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l3MouseClicked(evt);
            }
        });
        If1.getContentPane().add(l3);
        l3.setBounds(10, 40, 350, 210);

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel1.setText("Burberry BE2128 Eyeglasses ");
        If1.getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 20, 350, 50);

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel6.setText("Frame Price: 12640");
        If1.getContentPane().add(jLabel6);
        jLabel6.setBounds(310, 70, 200, 30);

        l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ssp/burberry-eye-be2128-3316-52-angle.jpg"))); // NOI18N
        l1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l1MouseClicked(evt);
            }
        });
        If1.getContentPane().add(l1);
        l1.setBounds(40, 310, 120, 60);

        l2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ssp/g1.jpg"))); // NOI18N
        l2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l2MouseClicked(evt);
            }
        });
        If1.getContentPane().add(l2);
        l2.setBounds(220, 310, 120, 60);

        jButton1.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jButton1.setText("Add to Cart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        If1.getContentPane().add(jButton1);
        jButton1.setBounds(400, 170, 150, 40);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Select Color");
        If1.getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 260, 100, 30);

        jButton4.setText("Payment");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        If1.getContentPane().add(jButton4);
        jButton4.setBounds(450, 290, 120, 23);

        jButton5.setText("go back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        If1.getContentPane().add(jButton5);
        jButton5.setBounds(460, 350, 69, 23);

        getContentPane().add(If1);
        If1.setBounds(70, 10, 651, 450);

        If2.setClosable(true);
        If2.setPreferredSize(new java.awt.Dimension(635, 450));
        If2.setVisible(false);
        If2.getContentPane().setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ssp/img-thing.jpg"))); // NOI18N
        If2.getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 60, 270, 250);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Gucci Eyeglasses 1533");
        If2.getContentPane().add(jLabel9);
        jLabel9.setBounds(330, 50, 310, 50);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Frame Price : 8920");
        If2.getContentPane().add(jLabel12);
        jLabel12.setBounds(340, 110, 170, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Add to cart");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        If2.getContentPane().add(jButton2);
        jButton2.setBounds(360, 240, 150, 50);

        jButton8.setText("Payment");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        If2.getContentPane().add(jButton8);
        jButton8.setBounds(140, 420, 90, 23);

        jButton9.setText("go back");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        If2.getContentPane().add(jButton9);
        jButton9.setBounds(370, 420, 69, 23);

        getContentPane().add(If2);
        If2.setBounds(60, 0, 635, 450);

        If3.setClosable(true);
        If3.setPreferredSize(new java.awt.Dimension(560, 430));
        If3.setVisible(false);
        If3.getContentPane().setLayout(null);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ssp/images.jpg"))); // NOI18N
        If3.getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 50, 280, 210);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Price : 2150");
        If3.getContentPane().add(jLabel11);
        jLabel11.setBounds(330, 110, 130, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("Gucci Gg 3768");
        If3.getContentPane().add(jLabel14);
        jLabel14.setBounds(330, 60, 190, 50);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Add to Cart");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        If3.getContentPane().add(jButton3);
        jButton3.setBounds(340, 203, 170, 40);

        jButton6.setText("Payment");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        If3.getContentPane().add(jButton6);
        jButton6.setBounds(100, 320, 100, 23);

        jButton7.setText("go back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        If3.getContentPane().add(jButton7);
        jButton7.setBounds(310, 320, 69, 23);

        getContentPane().add(If3);
        If3.setBounds(570, 300, 560, 430);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ssp/g2.jpg"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 280, 120, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ssp/g3.jpg"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(520, 270, 120, 70);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ssp/gw.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 20, 660, 220);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ssp/g1.jpg"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 280, 120, 60);

        jButton10.setText("Go back");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(270, 380, 71, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
      If2.setVisible(true);
        
        
    }//GEN-LAST:event_jLabel5MouseClicked

    private void l1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseClicked
        // TODO add your handling code here:
         l3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ssp/be2128.jpg"))); 
    }//GEN-LAST:event_l1MouseClicked

    private void l3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseClicked
        // TODO add your handling code here: 
    }//GEN-LAST:event_l3MouseClicked

    private void l2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseClicked
        // TODO add your handling code here:
          l3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ssp/bb2128.jpg")));
    }//GEN-LAST:event_l2MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
          If1.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try{
          Class.forName("java.sql.DriverManager");
          Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/aryan","root","root");
          Statement s = c.createStatement();
          ResultSet r = s.executeQuery("select * from gucci where Itemcode= 102;");
          while(r.next()){
               icode = r.getInt("itemcode");
            p = r.getInt("price");
            bname = r.getString("brandname");
            iname = r.getString("itemname");
            t = r.getString("itemtype");
          }
         
         }catch(Exception e){
         }
   
         System.out.println(ee);
                
       
                try{
                    Class.forName("java.sql.DriverManager");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/aryan","root","root");
                    Statement stmt=con.createStatement();
                    int a = stmt.executeUpdate("insert into bill_items values("+icode+",'"+t+"','"+bname+"','"+iname+"','"+p+"')");
                    JOptionPane.showMessageDialog(null, "Added successfully");
                }
                catch(Exception e){
                    {JOptionPane.showMessageDialog(null,e.getMessage());}
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
          Class.forName("java.sql.DriverManager");
          Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/aryan","root","root");
          Statement s = c.createStatement();
          ResultSet r = s.executeQuery("select * from gucci where Itemcode= 101;");
          while(r.next()){
               icode = r.getInt("itemcode");
            p = r.getInt("price");
            bname = r.getString("brandname");
            iname = r.getString("itemname");
            t = r.getString("itemtype");
          }
         }catch(Exception e){
         }
   
         System.out.println(ee);
                
       
                try{
                    Class.forName("java.sql.DriverManager");
                    Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/aryan","root","root");
                    Statement s=c.createStatement();
                    int a = s.executeUpdate("insert into bill_items values("+icode+",'"+t+"','"+bname+"','"+iname+"','"+p+"')");
                    JOptionPane.showMessageDialog(null, "Added successfully");
                }
                catch(Exception e){
                    {JOptionPane.showMessageDialog(null,e.getMessage());}
                }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        If3.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        bill a=new bill();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        frame4 a=new frame4();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
          Class.forName("java.sql.DriverManager");
          Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/aryan","root","root");
          Statement s = c.createStatement();
          ResultSet r = s.executeQuery("select * from gucci where Itemcode= 103;");
          while(r.next()){
               icode = r.getInt("itemcode");
            p = r.getInt("price");
            bname = r.getString("brandname");
            iname = r.getString("itemname");
            t = r.getString("itemtype");
          }
         }catch(Exception e){
         }
   
         System.out.println(ee);
                
       
                try{
                    Class.forName("java.sql.DriverManager");
                    Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/aryan","root","root");
                    Statement s=c.createStatement();
                    int a = s.executeUpdate("insert into bill_items values("+icode+",'"+t+"','"+bname+"','"+iname+"','"+p+"')");
                    JOptionPane.showMessageDialog(null, "Added successfully");
                }
                catch(Exception e){
                    {JOptionPane.showMessageDialog(null,e.getMessage());}
                }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        frame4 a=new frame4();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
          bill a=new bill();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
          bill a=new bill();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
          frame4 a=new frame4();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
         Frame3_1 a=new Frame3_1();
        a.setVisible(true);
        this.setVisible(false);
                                
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame If1;
    private javax.swing.JInternalFrame If2;
    private javax.swing.JInternalFrame If3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    // End of variables declaration//GEN-END:variables

    private static class con {

        private static void close() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public con() {
        }
    }
}
